name: Github Pages deployment

on:
  # push:
  #   branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.12.1'
      - uses: actions/configure-pages@v5
      - name: Install
        run: yarn
      - name: Test
        run: yarn test
      - name: Build
        run: yarn predeploy
        env:
          VITE_SUPABASE_URL: ${{ vars.VITE_SUPABASE_URL }}
          VITE_SUPABASE_KEY: ${{ vars.VITE_SUPABASE_KEY }}
          VITE_APP_VERSION: ${{ github.sha }}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4

  update_release:
    name: Update release in Supabase
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send update request
        env:
          SUPABASE_SERVICE_API_KEY: ${{ secrets.SUPABASE_SERVICE_API_KEY }}
        run: |
          curl -X POST \
            -L "${{ vars.VITE_SUPABASE_URL }}/rest/v1/Releases" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_API_KEY" \
            -H "apiKey: $SUPABASE_SERVICE_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"version\":\"${{ github.sha }}\"}"
